version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: imagevault
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - imagevaultnetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - imagevaultnetwork

  sbootapp:
    build:
      dockerfile: Dockerfile
    container_name: imagevaultapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - imagevaultnetwork
    environment:
      - POSTGRES_HOST=db
networks:
  imagevaultnetwork:
    driver: bridge



