package io.gituhub.jfelixy.imagevaultapi.application.jwt;

import io.gituhub.jfelixy.imagevaultapi.domain.AccessToken;
import io.gituhub.jfelixy.imagevaultapi.domain.entity.User;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jws;
import io.jsonwebtoken.JwtParser;
import io.jsonwebtoken.Jwts;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

@Service
public class JwtService {

    @Autowired
    private SecretKeyGenerator keyGenerator;

    public AccessToken generateToken(User user){

        SecretKey key = keyGenerator.getKey();//Token to sign
        Date expirationDate = generateExpirationDate();
        Map<String, Object> claims = generateTokenClaims(user);
        String token = Jwts
                        .builder()
                        .signWith(key)//Token to sign
                        .subject(user.getEmail())//Unique Id to identify user
                        .expiration(expirationDate)//Expiration
                        .claims(claims)//Information used in the token
                        .compact();

        return new AccessToken(token);
    }
    private Date generateExpirationDate(){
        //Capture current hour and include 60 seconds to expiration
        var expirationMinutes = 60;
        LocalDateTime now = LocalDateTime.now().plusMinutes(expirationMinutes);
        return Date.from(now.atZone(ZoneId.systemDefault()).toInstant());//Capture country reference through your system
    }

    //Method to insert claims in the token
    private Map<String, Object> generateTokenClaims(User user){
        Map<String, Object> claims = new HashMap<>();
        claims.put("name", user.getName());
        return claims;
    }

    public String getEmailFromToken(String tokenJwt) {
        // Creates a JwtParser instance using the secret key generated by keyGenerator
        JwtParser build = Jwts.parser()
                .verifyWith(keyGenerator.getKey()) // Verifies the token signature using the key
                .build();

        // Parses the signed JWT and extracts its claims (payload data)
        Jws<Claims> claims = build.parseSignedClaims(tokenJwt);

        // Retrieves the claims (body) from the JWT
        Claims cls = claims.getPayload();

        // Gets the subject field from the claims, which in this case is assumed to be the email
        String email = cls.getSubject();

        // Returns the extracted email
        return email;
    }

}
